[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "opp_ini"
authors = [{name = "anmomu92", email = "graziella@lumache"}]
dynamic = ["version", "description"]
